{% set name = "smart_open" %}
{% set version = "1.5.1" %}
{% set sha256 = "c5d43f71c5a8cae146bbfdd186d0a29c1cd4286cb69902e0cd3b1cd2aa7bf0b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

    
  run:
    - python
    - boto >=2.32
    - bz2file
    - requests

test:
  imports:
    - smart_open
    - smart_open.tests

about:
  home: https://github.com/RaRe-Technologies/smart_open
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python library for efficient streaming of large files'

  description: |
    smart_open is a Python 2 & Python 3 library 
    for efficient streaming of very large files
    from/to S3, HDFS, WebHDFS or local (compressed) files. 
  dev_url: https://github.com/RaRe-Technologies/smart_open

extra:
  recipe-maintainers:
    - souravsingh
    - tmylk
