{% set name = "smart_open" %}
{% set version = "1.5.7" %}
{% set sha256 = "f7b48789ffbbb73108fa3bf5f5431958611c752a56bc93ab9ffdf5de6e122c78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - boto >=2.32
    - bz2file
    - requests
    - boto3

test:
  requires:
    - mock
    - responses
  imports:
    - smart_open
    - smart_open.tests

about:
  home: https://github.com/RaRe-Technologies/smart_open
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python library for efficient streaming of large files'

  description: |
    smart_open is a Python 2 & Python 3 library 
    for efficient streaming of very large files
    from/to S3, HDFS, WebHDFS or local (compressed) files. 
  dev_url: https://github.com/RaRe-Technologies/smart_open

extra:
  recipe-maintainers:
    - souravsingh
    - menshikh-iv
